openapi: 3.0.0
info:
  title: Bookmark API
  version: 1.0.0
  description: bookmark actions
paths:
  /bookmark/:
    post:
      summary: Create a new bookmark
      description: Add a new bookmark with session information
      operationId: putBookmark
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sessionCode
                - sessionDescription
                - sessionTitle
              properties:
                sessionCode:
                  type: string
                  description: Unique code for the session
                sessionDescription:
                  type: string
                  description: Description of the session
                sessionTitle:
                  type: string
                  description: Title of the session
      responses:
        '201':
          description: Bookmark created successfully
        '400':
          description: Invalid input
        '500':
          description: Server error
    get:
      summary: Get all bookmarks
      description: Retrieve the list of all bookmarks
      operationId: getBookmark
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sessionCode:
                      type: string
                    sessionDescription:
                      type: string
                    sessionTitle:
                      type: string
        '500':
          description: Server error
