version: 0.2
env:
  variables:
    MAJOR: "1"
    MINOR: "1"
phases:
  install:
    commands:
      - ls
      - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update && sudo apt install terraform
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "build command"
      - STATE_BUCKET=$(aws ssm get-parameters --names terraform_state_bucket | jq -r '.Parameters[0].Value')
      - cd cicd-examples/lb-service-external-state
      - terraform init -backend-config="bucket=$STATE_BUCKET" -backend-config="key=lb-service-dev.tfstate" -backend-config="region=us-west-2"
      - terraform apply -var-file=../dev.tfvars -auto-approve
