# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3007e861284142573607c2c60bc23c02bc5e2df5aa8f3966091ca4a61cf8f6c4f0819911271e83c1086ce3135056caa92b73a055f5edb721d66447addba365d1

test:
  secret_key_base: e0159534f4f0beaf5b838aa81ad072c8e8798ebb6cdc2e1ba610060102ff6fefae02733c9c575f0fe03a2a2528467e59162677f904061be86fdad7e0510ebb73

# TODO: This value should not be checked into the repo! It's only here to keep this example simple!
production:
  secret_key_base: 3007e861284142573607c2c60bc23c02bc5e2df5aa8f3966091ca4a61cf8f6c4f0819911271e83c1086ce3135056caa92b73a055f5edb721d66447addba365d1
  # Secrets should be read from the environment!
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
